# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BatchIcp(object):
    def setupUi(self, BatchIcp):
        BatchIcp.setObjectName("BatchIcp")
        BatchIcp.resize(611, 531)
        BatchIcp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(BatchIcp)
        self.centralwidget.setObjectName("centralwidget")
        BatchIcp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BatchIcp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuBatch = QtWidgets.QMenu(self.menuFile)
        self.menuBatch.setObjectName("menuBatch")
        self.menuReach = QtWidgets.QMenu(self.menuBatch)
        self.menuReach.setObjectName("menuReach")
        self.menuQC = QtWidgets.QMenu(self.menuFile)
        self.menuQC.setObjectName("menuQC")
        self.menuFile_2 = QtWidgets.QMenu(self.menubar)
        self.menuFile_2.setObjectName("menuFile_2")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        BatchIcp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BatchIcp)
        self.statusbar.setObjectName("statusbar")
        BatchIcp.setStatusBar(self.statusbar)
        self.actionICP_OES = QtWidgets.QAction(BatchIcp)
        self.actionICP_OES.setObjectName("actionICP_OES")
        self.actionAAS = QtWidgets.QAction(BatchIcp)
        self.actionAAS.setObjectName("actionAAS")
        self.actionFarmal = QtWidgets.QAction(BatchIcp)
        self.actionFarmal.setObjectName("actionFarmal")
        self.actionpH = QtWidgets.QAction(BatchIcp)
        self.actionpH.setObjectName("actionpH")
        self.actionCr_VI = QtWidgets.QAction(BatchIcp)
        self.actionCr_VI.setObjectName("actionCr_VI")
        self.actionzidindyi = QtWidgets.QAction(BatchIcp)
        self.actionzidindyi.setObjectName("actionzidindyi")
        self.actionCustom = QtWidgets.QAction(BatchIcp)
        self.actionCustom.setObjectName("actionCustom")
        self.actionICP_OES_2 = QtWidgets.QAction(BatchIcp)
        self.actionICP_OES_2.setObjectName("actionICP_OES_2")
        self.actionFormal = QtWidgets.QAction(BatchIcp)
        self.actionFormal.setObjectName("actionFormal")
        self.actionpH_2 = QtWidgets.QAction(BatchIcp)
        self.actionpH_2.setObjectName("actionpH_2")
        self.actionCr_VI_2 = QtWidgets.QAction(BatchIcp)
        self.actionCr_VI_2.setObjectName("actionCr_VI_2")
        self.actionCustom_2 = QtWidgets.QAction(BatchIcp)
        self.actionCustom_2.setObjectName("actionCustom_2")
        self.actionBatch_2 = QtWidgets.QAction(BatchIcp)
        self.actionBatch_2.setObjectName("actionBatch_2")
        self.actionResult = QtWidgets.QAction(BatchIcp)
        self.actionResult.setObjectName("actionResult")
        self.actionOverTime = QtWidgets.QAction(BatchIcp)
        self.actionOverTime.setObjectName("actionOverTime")
        self.actionInput_Method = QtWidgets.QAction(BatchIcp)
        self.actionInput_Method.setObjectName("actionInput_Method")
        self.actionOutput_Method = QtWidgets.QAction(BatchIcp)
        self.actionOutput_Method.setObjectName("actionOutput_Method")
        self.actionSave_As = QtWidgets.QAction(BatchIcp)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionUser_Guide = QtWidgets.QAction(BatchIcp)
        self.actionUser_Guide.setObjectName("actionUser_Guide")
        self.actionAbout = QtWidgets.QAction(BatchIcp)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(BatchIcp)
        self.actionExit.setObjectName("actionExit")
        self.menuReach.addAction(self.actionBatch_2)
        self.menuReach.addAction(self.actionResult)
        self.menuBatch.addAction(self.actionICP_OES)
        self.menuBatch.addAction(self.actionAAS)
        self.menuBatch.addAction(self.actionFarmal)
        self.menuBatch.addAction(self.actionpH)
        self.menuBatch.addAction(self.actionCr_VI)
        self.menuBatch.addAction(self.menuReach.menuAction())
        self.menuBatch.addSeparator()
        self.menuBatch.addAction(self.actionCustom)
        self.menuQC.addAction(self.actionICP_OES_2)
        self.menuQC.addAction(self.actionFormal)
        self.menuQC.addAction(self.actionpH_2)
        self.menuQC.addAction(self.actionCr_VI_2)
        self.menuQC.addSeparator()
        self.menuQC.addAction(self.actionCustom_2)
        self.menuFile.addAction(self.menuBatch.menuAction())
        self.menuFile.addAction(self.menuQC.menuAction())
        self.menuFile.addAction(self.actionOverTime)
        self.menuFile_2.addAction(self.actionInput_Method)
        self.menuFile_2.addAction(self.actionOutput_Method)
        self.menuFile_2.addAction(self.actionSave_As)
        self.menuFile_2.addSeparator()
        self.menuFile_2.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BatchIcp)
        self.actionExit.triggered.connect(BatchIcp.close)
        self.actionInput_Method.triggered.connect(BatchIcp.update)
        QtCore.QMetaObject.connectSlotsByName(BatchIcp)

    def retranslateUi(self, BatchIcp):
        _translate = QtCore.QCoreApplication.translate
        BatchIcp.setWindowTitle(_translate("BatchIcp", "MainWindow"))
        self.menuFile.setTitle(_translate("BatchIcp", "Items"))
        self.menuBatch.setTitle(_translate("BatchIcp", "Batch"))
        self.menuReach.setTitle(_translate("BatchIcp", "Reach"))
        self.menuQC.setTitle(_translate("BatchIcp", "QC"))
        self.menuFile_2.setTitle(_translate("BatchIcp", "File"))
        self.menuHelp.setTitle(_translate("BatchIcp", "Help"))
        self.actionICP_OES.setText(_translate("BatchIcp", "ICP-OES"))
        self.actionAAS.setText(_translate("BatchIcp", "AAS"))
        self.actionFarmal.setText(_translate("BatchIcp", "Formal"))
        self.actionpH.setText(_translate("BatchIcp", "pH"))
        self.actionCr_VI.setText(_translate("BatchIcp", "Cr VI"))
        self.actionzidindyi.setText(_translate("BatchIcp", "zidindyi"))
        self.actionCustom.setText(_translate("BatchIcp", "Custom"))
        self.actionICP_OES_2.setText(_translate("BatchIcp", "ICP-OES"))
        self.actionFormal.setText(_translate("BatchIcp", "Formal"))
        self.actionpH_2.setText(_translate("BatchIcp", "pH"))
        self.actionCr_VI_2.setText(_translate("BatchIcp", "Cr VI"))
        self.actionCustom_2.setText(_translate("BatchIcp", "Custom"))
        self.actionBatch_2.setText(_translate("BatchIcp", "Batch"))
        self.actionResult.setText(_translate("BatchIcp", "Result"))
        self.actionOverTime.setText(_translate("BatchIcp", "OverTime"))
        self.actionInput_Method.setText(_translate("BatchIcp", "Input Method"))
        self.actionOutput_Method.setText(_translate("BatchIcp", "Output Method"))
        self.actionSave_As.setText(_translate("BatchIcp", "Save As"))
        self.actionUser_Guide.setText(_translate("BatchIcp", "User Guide"))
        self.actionAbout.setText(_translate("BatchIcp", "About"))
        self.actionExit.setText(_translate("BatchIcp", "Exit"))

