# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_w08reachauto.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReachAuto(object):
    def setupUi(self, ReachAuto):
        ReachAuto.setObjectName("ReachAuto")
        ReachAuto.resize(560, 390)
        font = QtGui.QFont()
        font.setPointSize(10)
        ReachAuto.setFont(font)
        ReachAuto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(ReachAuto)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 541, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget.sizePolicy().hasHeightForWidth())
        self.layoutWidget.setSizePolicy(sizePolicy)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout.addWidget(self.textEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        ReachAuto.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReachAuto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuBatch = QtWidgets.QMenu(self.menuFile)
        self.menuBatch.setObjectName("menuBatch")
        self.menuReach = QtWidgets.QMenu(self.menuBatch)
        self.menuReach.setObjectName("menuReach")
        self.menuQC = QtWidgets.QMenu(self.menuFile)
        self.menuQC.setObjectName("menuQC")
        self.menuFile_2 = QtWidgets.QMenu(self.menubar)
        self.menuFile_2.setObjectName("menuFile_2")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        ReachAuto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReachAuto)
        self.statusbar.setObjectName("statusbar")
        ReachAuto.setStatusBar(self.statusbar)
        self.actionICP_OES = QtWidgets.QAction(ReachAuto)
        self.actionICP_OES.setObjectName("actionICP_OES")
        self.actionAAS = QtWidgets.QAction(ReachAuto)
        self.actionAAS.setObjectName("actionAAS")
        self.actionFormal = QtWidgets.QAction(ReachAuto)
        self.actionFormal.setObjectName("actionFormal")
        self.actionpH = QtWidgets.QAction(ReachAuto)
        self.actionpH.setObjectName("actionpH")
        self.actionCr_VI = QtWidgets.QAction(ReachAuto)
        self.actionCr_VI.setObjectName("actionCr_VI")
        self.actionCustom = QtWidgets.QAction(ReachAuto)
        self.actionCustom.setObjectName("actionCustom")
        self.actionICP_OES_2 = QtWidgets.QAction(ReachAuto)
        self.actionICP_OES_2.setObjectName("actionICP_OES_2")
        self.actionFormal_2 = QtWidgets.QAction(ReachAuto)
        self.actionFormal_2.setObjectName("actionFormal_2")
        self.actionpH_2 = QtWidgets.QAction(ReachAuto)
        self.actionpH_2.setObjectName("actionpH_2")
        self.actionCr_VI_2 = QtWidgets.QAction(ReachAuto)
        self.actionCr_VI_2.setObjectName("actionCr_VI_2")
        self.actionCustom_2 = QtWidgets.QAction(ReachAuto)
        self.actionCustom_2.setObjectName("actionCustom_2")
        self.actionResult = QtWidgets.QAction(ReachAuto)
        self.actionResult.setObjectName("actionResult")
        self.actionOverTime = QtWidgets.QAction(ReachAuto)
        self.actionOverTime.setObjectName("actionOverTime")
        self.actionOutput_Method = QtWidgets.QAction(ReachAuto)
        self.actionOutput_Method.setObjectName("actionOutput_Method")
        self.actionMain_Window = QtWidgets.QAction(ReachAuto)
        self.actionMain_Window.setObjectName("actionMain_Window")
        self.actionUser_Guide = QtWidgets.QAction(ReachAuto)
        self.actionUser_Guide.setObjectName("actionUser_Guide")
        self.actionAbout = QtWidgets.QAction(ReachAuto)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(ReachAuto)
        self.actionExit.setObjectName("actionExit")
        self.actionAuto = QtWidgets.QAction(ReachAuto)
        self.actionAuto.setObjectName("actionAuto")
        self.menuReach.addAction(self.actionResult)
        self.menuReach.addAction(self.actionAuto)
        self.menuBatch.addAction(self.actionICP_OES)
        self.menuBatch.addAction(self.actionAAS)
        self.menuBatch.addAction(self.actionFormal)
        self.menuBatch.addAction(self.actionpH)
        self.menuBatch.addAction(self.actionCr_VI)
        self.menuBatch.addAction(self.menuReach.menuAction())
        self.menuBatch.addSeparator()
        self.menuBatch.addAction(self.actionCustom)
        self.menuQC.addAction(self.actionICP_OES_2)
        self.menuQC.addAction(self.actionFormal_2)
        self.menuQC.addAction(self.actionpH_2)
        self.menuQC.addAction(self.actionCr_VI_2)
        self.menuQC.addSeparator()
        self.menuQC.addAction(self.actionCustom_2)
        self.menuFile.addAction(self.menuBatch.menuAction())
        self.menuFile.addAction(self.menuQC.menuAction())
        self.menuFile.addAction(self.actionOverTime)
        self.menuFile_2.addAction(self.actionOutput_Method)
        self.menuFile_2.addAction(self.actionMain_Window)
        self.menuFile_2.addSeparator()
        self.menuFile_2.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ReachAuto)
        self.actionExit.triggered.connect(ReachAuto.close)
        self.actionOutput_Method.triggered.connect(ReachAuto.close)
        self.actionMain_Window.triggered.connect(ReachAuto.close)
        self.actionAAS.triggered.connect(ReachAuto.close)
        self.actionAbout.triggered.connect(ReachAuto.close)
        self.actionCr_VI.triggered.connect(ReachAuto.close)
        self.actionCr_VI_2.triggered.connect(ReachAuto.close)
        self.actionCustom.triggered.connect(ReachAuto.close)
        self.actionAuto.triggered.connect(ReachAuto.close)
        self.actionCustom_2.triggered.connect(ReachAuto.close)
        self.actionFormal.triggered.connect(ReachAuto.close)
        self.actionFormal_2.triggered.connect(ReachAuto.close)
        self.actionICP_OES.triggered.connect(ReachAuto.close)
        self.actionICP_OES_2.triggered.connect(ReachAuto.close)
        self.actionOverTime.triggered.connect(ReachAuto.close)
        self.actionResult.triggered.connect(ReachAuto.close)
        self.actionUser_Guide.triggered.connect(ReachAuto.close)
        self.actionpH.triggered.connect(ReachAuto.close)
        self.actionpH_2.triggered.connect(ReachAuto.close)
        self.pushButton.clicked.connect(ReachAuto.close)
        self.pushButton_2.clicked.connect(ReachAuto.close)
        self.pushButton_3.clicked.connect(ReachAuto.close)
        self.pushButton_4.clicked.connect(ReachAuto.close)
        QtCore.QMetaObject.connectSlotsByName(ReachAuto)

    def retranslateUi(self, ReachAuto):
        _translate = QtCore.QCoreApplication.translate
        ReachAuto.setWindowTitle(_translate("ReachAuto", "Reach-auto"))
        self.label_3.setText(_translate("ReachAuto", "Reach Auto"))
        self.textEdit.setToolTip(_translate("ReachAuto", "显示输入结果"))
        self.label.setText(_translate("ReachAuto", "Reach"))
        self.lineEdit.setToolTip(_translate("ReachAuto", "从该编号开始自动录结果"))
        self.pushButton.setStatusTip(_translate("ReachAuto", "点击开始自动录结果"))
        self.pushButton.setText(_translate("ReachAuto", "确认开始"))
        self.pushButton_2.setStatusTip(_translate("ReachAuto", "点击停止输入"))
        self.pushButton_2.setText(_translate("ReachAuto", "停止"))
        self.label_2.setText(_translate("ReachAuto", "编号对应物质"))
        self.lineEdit_2.setToolTip(_translate("ReachAuto", "文件路径"))
        self.pushButton_3.setStatusTip(_translate("ReachAuto", "选择文件"))
        self.pushButton_3.setText(_translate("ReachAuto", "选择文件"))
        self.lineEdit_3.setToolTip(_translate("ReachAuto", "输入要查询的编号"))
        self.pushButton_4.setToolTip(_translate("ReachAuto", "点击查询文件"))
        self.pushButton_4.setText(_translate("ReachAuto", "开始查询"))
        self.textEdit_2.setToolTip(_translate("ReachAuto", "显示查询结果"))
        self.menuFile.setTitle(_translate("ReachAuto", "Items"))
        self.menuBatch.setTitle(_translate("ReachAuto", "Batch"))
        self.menuReach.setTitle(_translate("ReachAuto", "Reach"))
        self.menuQC.setTitle(_translate("ReachAuto", "QC"))
        self.menuFile_2.setTitle(_translate("ReachAuto", "File"))
        self.menuHelp.setTitle(_translate("ReachAuto", "Help"))
        self.actionICP_OES.setText(_translate("ReachAuto", "ICP-OES"))
        self.actionICP_OES.setStatusTip(_translate("ReachAuto", "弹出ICP OES窗口界面"))
        self.actionAAS.setText(_translate("ReachAuto", "AAS"))
        self.actionAAS.setStatusTip(_translate("ReachAuto", "弹出AAS窗口界面"))
        self.actionFormal.setText(_translate("ReachAuto", "Formal"))
        self.actionFormal.setStatusTip(_translate("ReachAuto", "弹出Fomal窗口界面"))
        self.actionpH.setText(_translate("ReachAuto", "pH"))
        self.actionpH.setStatusTip(_translate("ReachAuto", "弹出pH窗口界面"))
        self.actionCr_VI.setText(_translate("ReachAuto", "Cr VI"))
        self.actionCr_VI.setStatusTip(_translate("ReachAuto", "弹出Cr VI窗口界面"))
        self.actionCustom.setText(_translate("ReachAuto", "Custom"))
        self.actionCustom.setStatusTip(_translate("ReachAuto", "弹出自定义窗口界面"))
        self.actionICP_OES_2.setText(_translate("ReachAuto", "ICP-OES"))
        self.actionICP_OES_2.setStatusTip(_translate("ReachAuto", "弹出重金属QC窗口界面"))
        self.actionFormal_2.setText(_translate("ReachAuto", "Formal"))
        self.actionFormal_2.setStatusTip(_translate("ReachAuto", "弹出Fomal-QC窗口界面"))
        self.actionpH_2.setText(_translate("ReachAuto", "pH"))
        self.actionpH_2.setStatusTip(_translate("ReachAuto", "弹出pH-QC窗口界面"))
        self.actionCr_VI_2.setText(_translate("ReachAuto", "Cr VI"))
        self.actionCr_VI_2.setStatusTip(_translate("ReachAuto", "弹出Cr VI-QC窗口界面"))
        self.actionCustom_2.setText(_translate("ReachAuto", "Custom"))
        self.actionCustom_2.setStatusTip(_translate("ReachAuto", "弹出自定义QC窗口界面"))
        self.actionResult.setText(_translate("ReachAuto", "Result"))
        self.actionResult.setStatusTip(_translate("ReachAuto", "弹出Reach-Result窗口界面"))
        self.actionOverTime.setText(_translate("ReachAuto", "OverTime"))
        self.actionOverTime.setStatusTip(_translate("ReachAuto", "弹出OT窗口界面"))
        self.actionOutput_Method.setText(_translate("ReachAuto", "Output Method"))
        self.actionOutput_Method.setStatusTip(_translate("ReachAuto", "导出方法设置，记录个性定制"))
        self.actionMain_Window.setText(_translate("ReachAuto", "Main Window"))
        self.actionMain_Window.setStatusTip(_translate("ReachAuto", "另存为"))
        self.actionUser_Guide.setText(_translate("ReachAuto", "User Guide"))
        self.actionUser_Guide.setStatusTip(_translate("ReachAuto", "弹出用户操作指南"))
        self.actionAbout.setText(_translate("ReachAuto", "About"))
        self.actionAbout.setStatusTip(_translate("ReachAuto", "关于作者"))
        self.actionExit.setText(_translate("ReachAuto", "Exit"))
        self.actionExit.setStatusTip(_translate("ReachAuto", "退出程序"))
        self.actionAuto.setText(_translate("ReachAuto", "Auto"))
        self.actionAuto.setStatusTip(_translate("ReachAuto", "弹出Reach-batch窗口界面"))

if __name__ == "__main__":
    import sys
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)  # 创建一个QApplication，也就是你要开发的软件app
    MainWindow = QtWidgets.QMainWindow()    # 创建一个QMainWindow，用来装载你需要的各种组件、控件
    ui = Ui_ReachAuto()                    # ui是Ui_MainWindow()类的实例化对象
    ui.setupUi(MainWindow)                  # 执行类中的setupUi方法，方法的参数是第二步中创建的QMainWindow
    MainWindow.show()                       # 执行QMainWindow的show()方法，显示这个QMainWindow
    sys.exit(app.exec_())                   # 使用exit()或者点击关闭按钮退出QApplication
