# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 531)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 60, 301, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 60, 301, 41))
        self.pushButton.setShortcut("")
        self.pushButton.setAutoRepeatDelay(310)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuBatch = QtWidgets.QMenu(self.menuFile)
        self.menuBatch.setObjectName("menuBatch")
        self.menuReach = QtWidgets.QMenu(self.menuBatch)
        self.menuReach.setObjectName("menuReach")
        self.menuQC = QtWidgets.QMenu(self.menuFile)
        self.menuQC.setObjectName("menuQC")
        self.menuFile_2 = QtWidgets.QMenu(self.menubar)
        self.menuFile_2.setObjectName("menuFile_2")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionICP_OES = QtWidgets.QAction(MainWindow)
        self.actionICP_OES.setObjectName("actionICP_OES")
        self.actionAAS = QtWidgets.QAction(MainWindow)
        self.actionAAS.setObjectName("actionAAS")
        self.actionFarmal = QtWidgets.QAction(MainWindow)
        self.actionFarmal.setObjectName("actionFarmal")
        self.actionpH = QtWidgets.QAction(MainWindow)
        self.actionpH.setObjectName("actionpH")
        self.actionCr_VI = QtWidgets.QAction(MainWindow)
        self.actionCr_VI.setObjectName("actionCr_VI")
        self.actionzidindyi = QtWidgets.QAction(MainWindow)
        self.actionzidindyi.setObjectName("actionzidindyi")
        self.actionCustom = QtWidgets.QAction(MainWindow)
        self.actionCustom.setObjectName("actionCustom")
        self.actionICP_OES_2 = QtWidgets.QAction(MainWindow)
        self.actionICP_OES_2.setObjectName("actionICP_OES_2")
        self.actionFormal = QtWidgets.QAction(MainWindow)
        self.actionFormal.setObjectName("actionFormal")
        self.actionpH_2 = QtWidgets.QAction(MainWindow)
        self.actionpH_2.setObjectName("actionpH_2")
        self.actionCr_VI_2 = QtWidgets.QAction(MainWindow)
        self.actionCr_VI_2.setObjectName("actionCr_VI_2")
        self.actionCustom_2 = QtWidgets.QAction(MainWindow)
        self.actionCustom_2.setObjectName("actionCustom_2")
        self.actionBatch_2 = QtWidgets.QAction(MainWindow)
        self.actionBatch_2.setObjectName("actionBatch_2")
        self.actionResult = QtWidgets.QAction(MainWindow)
        self.actionResult.setObjectName("actionResult")
        self.actionOverTime = QtWidgets.QAction(MainWindow)
        self.actionOverTime.setObjectName("actionOverTime")
        self.actionInput_Method = QtWidgets.QAction(MainWindow)
        self.actionInput_Method.setObjectName("actionInput_Method")
        self.actionOutput_Method = QtWidgets.QAction(MainWindow)
        self.actionOutput_Method.setObjectName("actionOutput_Method")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionUser_Guide = QtWidgets.QAction(MainWindow)
        self.actionUser_Guide.setObjectName("actionUser_Guide")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuReach.addAction(self.actionBatch_2)
        self.menuReach.addAction(self.actionResult)
        self.menuBatch.addAction(self.actionICP_OES)
        self.menuBatch.addAction(self.actionAAS)
        self.menuBatch.addAction(self.actionFarmal)
        self.menuBatch.addAction(self.actionpH)
        self.menuBatch.addAction(self.actionCr_VI)
        self.menuBatch.addAction(self.menuReach.menuAction())
        self.menuBatch.addSeparator()
        self.menuBatch.addAction(self.actionCustom)
        self.menuQC.addAction(self.actionICP_OES_2)
        self.menuQC.addAction(self.actionFormal)
        self.menuQC.addAction(self.actionpH_2)
        self.menuQC.addAction(self.actionCr_VI_2)
        self.menuQC.addSeparator()
        self.menuQC.addAction(self.actionCustom_2)
        self.menuFile.addAction(self.menuBatch.menuAction())
        self.menuFile.addAction(self.menuQC.menuAction())
        self.menuFile.addAction(self.actionOverTime)
        self.menuFile_2.addAction(self.actionInput_Method)
        self.menuFile_2.addAction(self.actionOutput_Method)
        self.menuFile_2.addAction(self.actionSave_As)
        self.menuFile_2.addSeparator()
        self.menuFile_2.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionInput_Method.triggered.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt;\">请输入中文名</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "选择文件"))
        self.menuFile.setTitle(_translate("MainWindow", "Items"))
        self.menuBatch.setTitle(_translate("MainWindow", "Batch"))
        self.menuReach.setTitle(_translate("MainWindow", "Reach"))
        self.menuQC.setTitle(_translate("MainWindow", "QC"))
        self.menuFile_2.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionICP_OES.setText(_translate("MainWindow", "ICP-OES"))
        self.actionAAS.setText(_translate("MainWindow", "AAS"))
        self.actionFarmal.setText(_translate("MainWindow", "Formal"))
        self.actionpH.setText(_translate("MainWindow", "pH"))
        self.actionCr_VI.setText(_translate("MainWindow", "Cr VI"))
        self.actionzidindyi.setText(_translate("MainWindow", "zidindyi"))
        self.actionCustom.setText(_translate("MainWindow", "Custom"))
        self.actionICP_OES_2.setText(_translate("MainWindow", "ICP-OES"))
        self.actionFormal.setText(_translate("MainWindow", "Formal"))
        self.actionpH_2.setText(_translate("MainWindow", "pH"))
        self.actionCr_VI_2.setText(_translate("MainWindow", "Cr VI"))
        self.actionCustom_2.setText(_translate("MainWindow", "Custom"))
        self.actionBatch_2.setText(_translate("MainWindow", "Batch"))
        self.actionResult.setText(_translate("MainWindow", "Result"))
        self.actionOverTime.setText(_translate("MainWindow", "OverTime"))
        self.actionInput_Method.setText(_translate("MainWindow", "Input Method"))
        self.actionOutput_Method.setText(_translate("MainWindow", "Output Method"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionUser_Guide.setText(_translate("MainWindow", "User Guide"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
if __name__ == "__main__":
    import sys
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)  # 创建一个QApplication，也就是你要开发的软件app
    MainWindow = QtWidgets.QMainWindow()    # 创建一个QMainWindow，用来装载你需要的各种组件、控件
    ui = Ui_MainWindow()                    # ui是Ui_MainWindow()类的实例化对象
    ui.setupUi(MainWindow)                  # 执行类中的setupUi方法，方法的参数是第二步中创建的QMainWindow
    MainWindow.show()                       # 执行QMainWindow的show()方法，显示这个QMainWindow
    sys.exit(app.exec_())                   # 使用exit()或者点击关闭按钮退出QApplication
