# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_ot.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 160, 271, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 0, 2, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 0, 5, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 0, 3, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 0, 4, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 0, 6, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout.addWidget(self.checkBox_18, 2, 3, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 1, 3, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 1, 1, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 1, 5, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_15, 2, 0, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout.addWidget(self.checkBox_20, 2, 5, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 1, 0, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout.addWidget(self.checkBox_28, 3, 6, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 1, 2, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout.addWidget(self.checkBox_16, 2, 1, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout.addWidget(self.checkBox_24, 3, 2, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout.addWidget(self.checkBox_22, 3, 0, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout.addWidget(self.checkBox_26, 3, 4, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout.addWidget(self.checkBox_14, 1, 6, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 1, 4, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout.addWidget(self.checkBox_19, 2, 4, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout.addWidget(self.checkBox_27, 3, 5, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout.addWidget(self.checkBox_21, 2, 6, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout.addWidget(self.checkBox_17, 2, 2, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout.addWidget(self.checkBox_25, 3, 3, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout.addWidget(self.checkBox_23, 3, 1, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout.addWidget(self.checkBox_29, 4, 0, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout.addWidget(self.checkBox_30, 4, 1, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout.addWidget(self.checkBox_31, 4, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(300, 160, 283, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_32 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_2.addWidget(self.checkBox_32, 0, 0, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_2.addWidget(self.checkBox_33, 0, 2, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout_2.addWidget(self.checkBox_34, 0, 5, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout_2.addWidget(self.checkBox_35, 0, 3, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_2.addWidget(self.checkBox_36, 0, 4, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_37.setObjectName("checkBox_37")
        self.gridLayout_2.addWidget(self.checkBox_37, 0, 6, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_38.setObjectName("checkBox_38")
        self.gridLayout_2.addWidget(self.checkBox_38, 0, 1, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_39.setObjectName("checkBox_39")
        self.gridLayout_2.addWidget(self.checkBox_39, 2, 3, 1, 1)
        self.checkBox_40 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_40.setObjectName("checkBox_40")
        self.gridLayout_2.addWidget(self.checkBox_40, 1, 3, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_41.setObjectName("checkBox_41")
        self.gridLayout_2.addWidget(self.checkBox_41, 1, 1, 1, 1)
        self.checkBox_42 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_42.setObjectName("checkBox_42")
        self.gridLayout_2.addWidget(self.checkBox_42, 1, 5, 1, 1)
        self.checkBox_43 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_43.setObjectName("checkBox_43")
        self.gridLayout_2.addWidget(self.checkBox_43, 2, 0, 1, 1)
        self.checkBox_44 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_44.setObjectName("checkBox_44")
        self.gridLayout_2.addWidget(self.checkBox_44, 2, 5, 1, 1)
        self.checkBox_45 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_45.setObjectName("checkBox_45")
        self.gridLayout_2.addWidget(self.checkBox_45, 1, 0, 1, 1)
        self.checkBox_46 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_46.setObjectName("checkBox_46")
        self.gridLayout_2.addWidget(self.checkBox_46, 3, 6, 1, 1)
        self.checkBox_47 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_47.setObjectName("checkBox_47")
        self.gridLayout_2.addWidget(self.checkBox_47, 1, 2, 1, 1)
        self.checkBox_48 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_48.setObjectName("checkBox_48")
        self.gridLayout_2.addWidget(self.checkBox_48, 2, 1, 1, 1)
        self.checkBox_49 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_49.setObjectName("checkBox_49")
        self.gridLayout_2.addWidget(self.checkBox_49, 3, 2, 1, 1)
        self.checkBox_50 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_50.setObjectName("checkBox_50")
        self.gridLayout_2.addWidget(self.checkBox_50, 3, 0, 1, 1)
        self.checkBox_51 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_51.setObjectName("checkBox_51")
        self.gridLayout_2.addWidget(self.checkBox_51, 3, 4, 1, 1)
        self.checkBox_52 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_52.setObjectName("checkBox_52")
        self.gridLayout_2.addWidget(self.checkBox_52, 1, 6, 1, 1)
        self.checkBox_53 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_53.setObjectName("checkBox_53")
        self.gridLayout_2.addWidget(self.checkBox_53, 1, 4, 1, 1)
        self.checkBox_54 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_54.setObjectName("checkBox_54")
        self.gridLayout_2.addWidget(self.checkBox_54, 2, 4, 1, 1)
        self.checkBox_55 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_55.setObjectName("checkBox_55")
        self.gridLayout_2.addWidget(self.checkBox_55, 3, 5, 1, 1)
        self.checkBox_56 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_56.setObjectName("checkBox_56")
        self.gridLayout_2.addWidget(self.checkBox_56, 2, 6, 1, 1)
        self.checkBox_57 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_57.setObjectName("checkBox_57")
        self.gridLayout_2.addWidget(self.checkBox_57, 2, 2, 1, 1)
        self.checkBox_58 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_58.setObjectName("checkBox_58")
        self.gridLayout_2.addWidget(self.checkBox_58, 3, 3, 1, 1)
        self.checkBox_59 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_59.setObjectName("checkBox_59")
        self.gridLayout_2.addWidget(self.checkBox_59, 3, 1, 1, 1)
        self.checkBox_60 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_60.setObjectName("checkBox_60")
        self.gridLayout_2.addWidget(self.checkBox_60, 4, 0, 1, 1)
        self.checkBox_61 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_61.setObjectName("checkBox_61")
        self.gridLayout_2.addWidget(self.checkBox_61, 4, 1, 1, 1)
        self.checkBox_62 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_62.setObjectName("checkBox_62")
        self.gridLayout_2.addWidget(self.checkBox_62, 4, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 410, 271, 91))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 120, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 120, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 60, 271, 41))
        self.lineEdit.setToolTip("")
        self.lineEdit.setStatusTip("")
        self.lineEdit.setWhatsThis("")
        self.lineEdit.setAccessibleName("")
        self.lineEdit.setAccessibleDescription("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 60, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 410, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 0, 90, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 320, 300, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(280, 160, 20, 141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "1"))
        self.checkBox_3.setText(_translate("MainWindow", "3"))
        self.checkBox_6.setText(_translate("MainWindow", "6"))
        self.checkBox_4.setText(_translate("MainWindow", "4"))
        self.checkBox_5.setText(_translate("MainWindow", "5"))
        self.checkBox_7.setText(_translate("MainWindow", "7"))
        self.checkBox_2.setText(_translate("MainWindow", "2"))
        self.checkBox_18.setText(_translate("MainWindow", "18"))
        self.checkBox_11.setText(_translate("MainWindow", "11"))
        self.checkBox_9.setText(_translate("MainWindow", "9"))
        self.checkBox_13.setText(_translate("MainWindow", "13"))
        self.checkBox_15.setText(_translate("MainWindow", "15"))
        self.checkBox_20.setText(_translate("MainWindow", "20"))
        self.checkBox_8.setText(_translate("MainWindow", "8"))
        self.checkBox_28.setText(_translate("MainWindow", "28"))
        self.checkBox_10.setText(_translate("MainWindow", "10"))
        self.checkBox_16.setText(_translate("MainWindow", "16"))
        self.checkBox_24.setText(_translate("MainWindow", "24"))
        self.checkBox_22.setText(_translate("MainWindow", "22"))
        self.checkBox_26.setText(_translate("MainWindow", "26"))
        self.checkBox_14.setText(_translate("MainWindow", "14"))
        self.checkBox_12.setText(_translate("MainWindow", "12"))
        self.checkBox_19.setText(_translate("MainWindow", "19"))
        self.checkBox_27.setText(_translate("MainWindow", "27"))
        self.checkBox_21.setText(_translate("MainWindow", "21"))
        self.checkBox_17.setText(_translate("MainWindow", "17"))
        self.checkBox_25.setText(_translate("MainWindow", "25"))
        self.checkBox_23.setText(_translate("MainWindow", "23"))
        self.checkBox_29.setText(_translate("MainWindow", "29"))
        self.checkBox_30.setText(_translate("MainWindow", "30"))
        self.checkBox_31.setText(_translate("MainWindow", "31"))
        self.checkBox_32.setText(_translate("MainWindow", "1"))
        self.checkBox_33.setText(_translate("MainWindow", "3"))
        self.checkBox_34.setText(_translate("MainWindow", "6"))
        self.checkBox_35.setText(_translate("MainWindow", "4"))
        self.checkBox_36.setText(_translate("MainWindow", "5"))
        self.checkBox_37.setText(_translate("MainWindow", "7"))
        self.checkBox_38.setText(_translate("MainWindow", "2"))
        self.checkBox_39.setText(_translate("MainWindow", "18"))
        self.checkBox_40.setText(_translate("MainWindow", "11"))
        self.checkBox_41.setText(_translate("MainWindow", "9"))
        self.checkBox_42.setText(_translate("MainWindow", "13"))
        self.checkBox_43.setText(_translate("MainWindow", "15"))
        self.checkBox_44.setText(_translate("MainWindow", "20"))
        self.checkBox_45.setText(_translate("MainWindow", "8"))
        self.checkBox_46.setText(_translate("MainWindow", "28"))
        self.checkBox_47.setText(_translate("MainWindow", "10"))
        self.checkBox_48.setText(_translate("MainWindow", "16"))
        self.checkBox_49.setText(_translate("MainWindow", "24"))
        self.checkBox_50.setText(_translate("MainWindow", "22"))
        self.checkBox_51.setText(_translate("MainWindow", "26"))
        self.checkBox_52.setText(_translate("MainWindow", "14"))
        self.checkBox_53.setText(_translate("MainWindow", "12"))
        self.checkBox_54.setText(_translate("MainWindow", "19"))
        self.checkBox_55.setText(_translate("MainWindow", "27"))
        self.checkBox_56.setText(_translate("MainWindow", "21"))
        self.checkBox_57.setText(_translate("MainWindow", "17"))
        self.checkBox_58.setText(_translate("MainWindow", "25"))
        self.checkBox_59.setText(_translate("MainWindow", "23"))
        self.checkBox_60.setText(_translate("MainWindow", "29"))
        self.checkBox_61.setText(_translate("MainWindow", "30"))
        self.checkBox_62.setText(_translate("MainWindow", "31"))
        self.label.setText(_translate("MainWindow", "周末为工作日："))
        self.label_2.setText(_translate("MainWindow", "工作日为假期："))
        self.pushButton.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_2.setText(_translate("MainWindow", "确认开始"))
        self.label_3.setText(_translate("MainWindow", "加班申请"))
        self.label_4.setText(_translate("MainWindow", "消息显示"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)  # 创建一个QApplication，也就是你要开发的软件app
    MainWindow = QtWidgets.QMainWindow()    # 创建一个QMainWindow，用来装载你需要的各种组件、控件
    ui = Ui_MainWindow()                    # ui是Ui_MainWindow()类的实例化对象
    ui.setupUi(MainWindow)                  # 执行类中的setupUi方法，方法的参数是第二步中创建的QMainWindow
    MainWindow.show()                       # 执行QMainWindow的show()方法，显示这个QMainWindow
    sys.exit(app.exec_())                   # 使用exit()或者点击关闭按钮退出QApplication
