# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BatchAas(object):
    def setupUi(self, BatchAas):
        BatchAas.setObjectName("BatchAas")
        BatchAas.resize(192, 172)
        BatchAas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        BatchAas.setToolTip("")
        BatchAas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(BatchAas)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 171, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        BatchAas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BatchAas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 192, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuBatch = QtWidgets.QMenu(self.menuFile)
        self.menuBatch.setObjectName("menuBatch")
        self.menuReach = QtWidgets.QMenu(self.menuBatch)
        self.menuReach.setObjectName("menuReach")
        self.menuQC = QtWidgets.QMenu(self.menuFile)
        self.menuQC.setObjectName("menuQC")
        self.menuFile_2 = QtWidgets.QMenu(self.menubar)
        self.menuFile_2.setObjectName("menuFile_2")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        BatchAas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BatchAas)
        self.statusbar.setObjectName("statusbar")
        BatchAas.setStatusBar(self.statusbar)
        self.actionICP_OES = QtWidgets.QAction(BatchAas)
        self.actionICP_OES.setObjectName("actionICP_OES")
        self.actionAAS = QtWidgets.QAction(BatchAas)
        self.actionAAS.setObjectName("actionAAS")
        self.actionFarmal = QtWidgets.QAction(BatchAas)
        self.actionFarmal.setObjectName("actionFarmal")
        self.actionpH = QtWidgets.QAction(BatchAas)
        self.actionpH.setObjectName("actionpH")
        self.actionCr_VI = QtWidgets.QAction(BatchAas)
        self.actionCr_VI.setObjectName("actionCr_VI")
        self.actionzidindyi = QtWidgets.QAction(BatchAas)
        self.actionzidindyi.setObjectName("actionzidindyi")
        self.actionCustom = QtWidgets.QAction(BatchAas)
        self.actionCustom.setObjectName("actionCustom")
        self.actionICP_OES_2 = QtWidgets.QAction(BatchAas)
        self.actionICP_OES_2.setObjectName("actionICP_OES_2")
        self.actionFormal = QtWidgets.QAction(BatchAas)
        self.actionFormal.setObjectName("actionFormal")
        self.actionpH_2 = QtWidgets.QAction(BatchAas)
        self.actionpH_2.setObjectName("actionpH_2")
        self.actionCr_VI_2 = QtWidgets.QAction(BatchAas)
        self.actionCr_VI_2.setObjectName("actionCr_VI_2")
        self.actionCustom_2 = QtWidgets.QAction(BatchAas)
        self.actionCustom_2.setObjectName("actionCustom_2")
        self.actionBatch_2 = QtWidgets.QAction(BatchAas)
        self.actionBatch_2.setObjectName("actionBatch_2")
        self.actionResult = QtWidgets.QAction(BatchAas)
        self.actionResult.setObjectName("actionResult")
        self.actionOverTime = QtWidgets.QAction(BatchAas)
        self.actionOverTime.setObjectName("actionOverTime")
        self.actionInput_Method = QtWidgets.QAction(BatchAas)
        self.actionInput_Method.setObjectName("actionInput_Method")
        self.actionOutput_Method = QtWidgets.QAction(BatchAas)
        self.actionOutput_Method.setObjectName("actionOutput_Method")
        self.actionSave_As = QtWidgets.QAction(BatchAas)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionUser_Guide = QtWidgets.QAction(BatchAas)
        self.actionUser_Guide.setObjectName("actionUser_Guide")
        self.actionAbout = QtWidgets.QAction(BatchAas)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(BatchAas)
        self.actionExit.setObjectName("actionExit")
        self.menuReach.addAction(self.actionBatch_2)
        self.menuReach.addAction(self.actionResult)
        self.menuBatch.addAction(self.actionICP_OES)
        self.menuBatch.addAction(self.actionAAS)
        self.menuBatch.addAction(self.actionFarmal)
        self.menuBatch.addAction(self.actionpH)
        self.menuBatch.addAction(self.actionCr_VI)
        self.menuBatch.addAction(self.menuReach.menuAction())
        self.menuBatch.addSeparator()
        self.menuBatch.addAction(self.actionCustom)
        self.menuQC.addAction(self.actionICP_OES_2)
        self.menuQC.addAction(self.actionFormal)
        self.menuQC.addAction(self.actionpH_2)
        self.menuQC.addAction(self.actionCr_VI_2)
        self.menuQC.addSeparator()
        self.menuQC.addAction(self.actionCustom_2)
        self.menuFile.addAction(self.menuBatch.menuAction())
        self.menuFile.addAction(self.menuQC.menuAction())
        self.menuFile.addAction(self.actionOverTime)
        self.menuFile_2.addAction(self.actionInput_Method)
        self.menuFile_2.addAction(self.actionOutput_Method)
        self.menuFile_2.addAction(self.actionSave_As)
        self.menuFile_2.addSeparator()
        self.menuFile_2.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

    def ui_batch_aas(self):
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setToolTipDuration(-1)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)


        self.retranslateUi(BatchAas)
        self.actionExit.triggered.connect(BatchAas.close)
        self.actionAAS.triggered.connect(self.ui_batch_aas)
        self.actionInput_Method.triggered.connect(BatchAas.update)
        QtCore.QMetaObject.connectSlotsByName(BatchAas)

    def retranslateUi(self, BatchAas):
        _translate = QtCore.QCoreApplication.translate
        BatchAas.setWindowTitle(_translate("BatchAas", "MainWindow"))
        self.label.setText(_translate("BatchAas", "Batch生成AAS格式"))
        self.pushButton.setText(_translate("BatchAas", "选择文件"))
        self.lineEdit.setToolTip(_translate("BatchAas", "<html><head/><body><p>文件路径</p></body></html>"))
        self.pushButton_2.setText(_translate("BatchAas", "确认"))
        self.menuFile.setTitle(_translate("BatchAas", "Items"))
        self.menuBatch.setTitle(_translate("BatchAas", "Batch"))
        self.menuReach.setTitle(_translate("BatchAas", "Reach"))
        self.menuQC.setTitle(_translate("BatchAas", "QC"))
        self.menuFile_2.setTitle(_translate("BatchAas", "File"))
        self.menuHelp.setTitle(_translate("BatchAas", "Help"))
        self.actionICP_OES.setText(_translate("BatchAas", "ICP-OES"))
        self.actionAAS.setText(_translate("BatchAas", "AAS"))
        self.actionFarmal.setText(_translate("BatchAas", "Formal"))
        self.actionpH.setText(_translate("BatchAas", "pH"))
        self.actionCr_VI.setText(_translate("BatchAas", "Cr VI"))
        self.actionzidindyi.setText(_translate("BatchAas", "zidindyi"))
        self.actionCustom.setText(_translate("BatchAas", "Custom"))
        self.actionICP_OES_2.setText(_translate("BatchAas", "ICP-OES"))
        self.actionFormal.setText(_translate("BatchAas", "Formal"))
        self.actionpH_2.setText(_translate("BatchAas", "pH"))
        self.actionCr_VI_2.setText(_translate("BatchAas", "Cr VI"))
        self.actionCustom_2.setText(_translate("BatchAas", "Custom"))
        self.actionBatch_2.setText(_translate("BatchAas", "Batch"))
        self.actionResult.setText(_translate("BatchAas", "Result"))
        self.actionOverTime.setText(_translate("BatchAas", "OverTime"))
        self.actionInput_Method.setText(_translate("BatchAas", "Input Method"))
        self.actionOutput_Method.setText(_translate("BatchAas", "Output Method"))
        self.actionSave_As.setText(_translate("BatchAas", "Save As"))
        self.actionUser_Guide.setText(_translate("BatchAas", "User Guide"))
        self.actionAbout.setText(_translate("BatchAas", "About"))
        self.actionExit.setText(_translate("BatchAas", "Exit"))
if __name__ == "__main__":
    import sys
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)  # 创建一个QApplication，也就是你要开发的软件app
    MainWindow = QtWidgets.QMainWindow()  # 创建一个QMainWindow，用来装载你需要的各种组件、控件
    ui = Ui_BatchAas()  # ui是Ui_MainWindow()类的实例化对象
    ui.setupUi(MainWindow)  # 执行类中的setupUi方法，方法的参数是第二步中创建的QMainWindow
    MainWindow.show()  # 执行QMainWindow的show()方法，显示这个QMainWindow
    sys.exit(app.exec_())  # 使用exit()或者点击关闭按钮退出QApplication
